/** Common returner-friendly skill suggestions for autocomplete. */
export const SKILL_SUGGESTIONS = [
  "Project Management",
  "Stakeholder Management",
  "Microsoft Excel",
  "Microsoft Office",
  "Customer Service",
  "Communication",
  "Team Leadership",
  "People Management",
  "Administration",
  "Data Analysis",
  "CRM",
  "Salesforce",
  "Marketing",
  "Content Writing",
  "Social Media",
  "Bookkeeping",
  "Accounting",
  "HR",
  "Recruitment",
  "Teaching",
  "Training",
  "Coaching",
  "Healthcare",
  "Nursing",
  "Retail",
  "Sales",
  "Python",
  "SQL",
  "JavaScript",
  "Problem Solving",
  "Time Management",
  "Organisation",
  "Research",
  "Presentation Skills",
  "Negotiation",
  "Event Planning",
  "Fundraising",
  "Safeguarding",
  "First Aid",
] as const;
