/** Common skill suggestions across professions — not IT-only. */
export const SKILL_SUGGESTIONS = [
  "Lesson planning",
  "Assessment design",
  "Classroom leadership",
  "Safeguarding",
  "Commercial installs",
  "Electrical testing",
  "Fault diagnosis",
  "Health & safety",
  "Brand identity",
  "Visual design",
  "Client briefing",
  "Typography",
  "Menu design",
  "Food costing",
  "Kitchen leadership",
  "Food hygiene",
  "Programme delivery",
  "Stakeholder management",
  "Risk management",
  "Budget control",
  "Project Management",
  "Customer Service",
  "Communication",
  "Team Leadership",
  "People Management",
  "Administration",
  "Data Analysis",
  "CRM",
  "Marketing",
  "Content Writing",
  "Social Media",
  "Bookkeeping",
  "Accounting",
  "Recruitment",
  "Teaching",
  "Training",
  "Coaching",
  "Nursing",
  "Retail",
  "Sales",
  "Python",
  "SQL",
  "JavaScript",
  "TypeScript",
  "React",
  "Problem Solving",
  "Time Management",
  "Organisation",
  "Research",
  "Presentation Skills",
  "Negotiation",
  "Event Planning",
  "First Aid",
] as const;
